import React from "react";

// The loop data is fetched from /src/components/loopInput.tsx
// and used by /src/contexts/mainContext.tsx to create timeSteps and other things...
export type loopData = {
  pastLoopCount: number;
  loopCount: number;
};

// the time-step types
export enum timeStepTypes {
  work = 0,
  short = 1,
  long = 2,
}

// the time-step state types
export enum timeStepStateTypes {
  pending = 0,
  active = 1,
  finished = 2,
}

// The time-step type that will be generated by mainContext
// and to be used by timeStepMenu and time-managing
export type timeStepData = {
  type: timeStepTypes;
  stepTime: number;
  startingTime: number;
};

// The interface for main-context
// interface mainContextInterface
export interface mainContextInterface {
  state: number;
  loopData: loopData;
  runningStep: number;
  isPaused: boolean;
  timeSteps: Array<timeStepData>;
  setLoopData: React.Dispatch<React.SetStateAction<loopData>>;
  cancelTimer: Function;
  pauseTimer: Function;
  resumeTimer: Function;
  startNextStep: Function;
}
